# Generated by Django 3.2.4 on 2021-07-04 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forename', models.CharField(blank=True, max_length=20, verbose_name='First name')),
                ('surname', models.CharField(blank=True, max_length=20, verbose_name='Last name')),
                ('street1', models.CharField(blank=True, max_length=256, verbose_name='Street 1')),
                ('street2', models.CharField(blank=True, max_length=256, verbose_name='Street 2')),
                ('city', models.CharField(blank=True, max_length=256, verbose_name='City')),
                ('zip_code', models.CharField(blank=True, max_length=256, verbose_name='ZIP/Postal code')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=256, verbose_name='Phone')),
                ('date_from', models.DateTimeField(blank=True, null=True, verbose_name='From')),
                ('date_until', models.DateTimeField(blank=True, null=True, verbose_name='Until')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('booking_id', models.CharField(blank=True, max_length=100, verbose_name='Booking ID')),
                ('time_period', models.PositiveIntegerField(blank=True, null=True, verbose_name='Time period')),
                ('time_unit', models.CharField(blank=True, default='day', max_length=64, verbose_name='Time unit')),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=36, null=True, verbose_name='Total')),
            ],
            options={
                'ordering': ['-creation_date'],
            },
        ),
        migrations.CreateModel(
            name='BookingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(verbose_name='Slug')),
            ],
        ),
        migrations.CreateModel(
            name='BookingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=36, null=True, verbose_name='Subtotal')),
                ('object_id', models.PositiveIntegerField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.booking', verbose_name='Booking')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-booking__creation_date'],
            },
        ),
        migrations.CreateModel(
            name='BookingError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=1000, verbose_name='Message')),
                ('details', models.TextField(blank=True, max_length=4000, verbose_name='Details')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.booking', verbose_name='Booking')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.bookingstatus', verbose_name='Booking status'),
        ),
        migrations.AddField(
            model_name='booking',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sessions.session', verbose_name='Session'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
