# Generated by Django 3.2.4 on 2021-09-13 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20210913_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation Date'),
        ),
    ]
